--=======================================================
--  This code is generated by https://datacipy.cz/tools/kitgen
--=======================================================

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY thermometer IS
    PORT (
		--------- CLOCK ---------
		CLK_50 : IN std_logic;

		--------- LM75 ---------
		LM75_I2C_SCL : INOUT std_logic;
		LM75_I2C_SDA : INOUT std_logic;


		--------- SEG7 ---------
		DIGIT : OUT std_logic_vector(3 DOWNTO 0) := "1111";
		SEGMENT : OUT std_logic_vector(7 DOWNTO 0) := "11111111"


    );
END ENTITY;

ARCHITECTURE rtl OF thermometer IS
--=======================================================
--  SIGNAL declarations
--=======================================================

	SIGNAL out16b : std_logic_vector(15 DOWNTO 0) := x"0000";
	SIGNAL clk_1k : std_logic;
	signal temp:std_logic_vector(8 downto 0);

BEGIN

--=======================================================
--  Structural coding
--=======================================================

	-- delicka frekvence pro LED displej
	-- bez ni je obnovovani prilis rychle a displej necitelny

	divider : ENTITY work.freqdiv PORT MAP (clk => clk_50, clkout => clk_1k);

	-- Multiplexovany displej LED

	disp : ENTITY work.segmuxnum PORT MAP (clk_1k, unsigned(out16b),
		segment(0), segment(1), segment(2), segment(3),
		segment(4), segment(5), segment(6), segment(7),
		digit(0), digit(1), digit(2), digit(3));
		
	-- teplomer
	
	lm75: ENTITY work.pmod_temp_sensor_tcn75a PORT MAP (
	clk=>clk_50,
	reset_n=>'1', 
	scl=>LM75_I2C_SCL,
	sda=>LM75_I2C_SDA,
	temperature=> temp
	);

	-- Binarni verze
	
	out16b(11 downto 3) <= temp
	
	-- BCD verze (zakomentovat predchozi prirazeni a odkomentovat nasledujici radek)
	-- bcdconv: entity work.bcd port map (temp(8 downto 1),out16b(9 downto 0));
	
	

END ARCHITECTURE;
