--=======================================================
--  This code is generated by https://datacipy.cz/tools/kitgen
--=======================================================

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY BCD_counter IS
	PORT (
		--------- CLOCK ---------
		CLK_50 : IN std_logic;
		--------- KEY ---------
		KEY : IN std_logic_vector(3 DOWNTO 0);
		--------- SEG7 ---------
		DIGIT : OUT std_logic_vector(3 DOWNTO 0) := "1111";
		SEGMENT : OUT std_logic_vector(7 DOWNTO 0) := "11111111"
	);
END ENTITY;

ARCHITECTURE rtl OF BCD_counter IS
	--=======================================================
	--  SIGNAL declarations
	--=======================================================
	SIGNAL out16b : std_logic_vector(15 DOWNTO 0) := x"0000";
	SIGNAL clk_1k : std_logic;
	SIGNAL clk_1hz : std_logic;
	SIGNAL carry : std_logic;

BEGIN

	--=======================================================
	--  Structural coding
	--=======================================================

	-- delicka frekvence pro LED displej
	-- bez ni je obnovovani prilis rychle a displej necitelny

	divider : ENTITY work.freqdiv PORT MAP (clk => clk_50, clkout => clk_1k);

	-- Multiplexovany displej LED

	disp : ENTITY work.segmuxnum PORT MAP (clk_1k, unsigned(out16b),
		segment(0), segment(1), segment(2), segment(3),
		segment(4), segment(5), segment(6), segment(7),
		digit(0), digit(1), digit(2), digit(3));

	-- Citac BCD
	-- automaticky
	cnt1 : ENTITY work.counter4BCD PORT MAP (
		"0000",
		'0',
		clk_1hz,
		'0',
		out16b(3 DOWNTO 0),
		carry
		);

	-- prenos nastavime do vystupu jako bit 4
	out16b(4) <= carry;
	-- delicka frekvence pro pocitani

	divider1hz : ENTITY work.freqdiv GENERIC MAP (freqout => 1) PORT MAP (clk => clk_50, clkout => clk_1hz);
END ARCHITECTURE;