vcom ../busses.vhd
vcom ../io81.vhd
vcom ../lcd97.vhd
vcom ../modes97.vhd
vcom ../res_clk.vhd
vcom ../video81.vhd
vcom ../top.vhd
vcom ../zx97tb.vhd
vcom ../zx97.vhd
vcom ../zx97tb.vhd
vcom ../sim_cfg.vhd
